version: '3'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: shido
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: vehicle-sales-manager
    ports:
      - "5432:5432"
    networks:
      - "intranet"

networks:
  intranet: